/**
 * This class is generated by jOOQ
 */
package eu.lifewatchgreece.metacatalogue.models.tables;


import eu.lifewatchgreece.metacatalogue.models.Keys;
import eu.lifewatchgreece.metacatalogue.models.Metacatalogue;
import eu.lifewatchgreece.metacatalogue.models.tables.records.SettingsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Settings extends TableImpl<SettingsRecord> {

	private static final long serialVersionUID = -1975897317;

	/**
	 * The reference instance of <code>metacatalogue.settings</code>
	 */
	public static final Settings SETTINGS = new Settings();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<SettingsRecord> getRecordType() {
		return SettingsRecord.class;
	}

	/**
	 * The column <code>metacatalogue.settings.id</code>.
	 */
	public final TableField<SettingsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>metacatalogue.settings.name</code>.
	 */
	public final TableField<SettingsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>metacatalogue.settings.value</code>.
	 */
	public final TableField<SettingsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>metacatalogue.settings.last_modified</code>.
	 */
	public final TableField<SettingsRecord, Timestamp> LAST_MODIFIED = createField("last_modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>metacatalogue.settings.about</code>.
	 */
	public final TableField<SettingsRecord, String> ABOUT = createField("about", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * Create a <code>metacatalogue.settings</code> table reference
	 */
	public Settings() {
		this("settings", null);
	}

	/**
	 * Create an aliased <code>metacatalogue.settings</code> table reference
	 */
	public Settings(String alias) {
		this(alias, SETTINGS);
	}

	private Settings(String alias, Table<SettingsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Settings(String alias, Table<SettingsRecord> aliased, Field<?>[] parameters) {
		super(alias, Metacatalogue.METACATALOGUE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<SettingsRecord, UInteger> getIdentity() {
		return Keys.IDENTITY_SETTINGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<SettingsRecord> getPrimaryKey() {
		return Keys.KEY_SETTINGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<SettingsRecord>> getKeys() {
		return Arrays.<UniqueKey<SettingsRecord>>asList(Keys.KEY_SETTINGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Settings as(String alias) {
		return new Settings(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Settings rename(String name) {
		return new Settings(name, null);
	}
}
