/**
 * This class is generated by jOOQ
 */
package eu.lifewatchgreece.metacatalogue.models;


import eu.lifewatchgreece.metacatalogue.models.tables.Datasets;
import eu.lifewatchgreece.metacatalogue.models.tables.Logs;
import eu.lifewatchgreece.metacatalogue.models.tables.Settings;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Metacatalogue extends SchemaImpl {

	private static final long serialVersionUID = 1753681482;

	/**
	 * The reference instance of <code>metacatalogue</code>
	 */
	public static final Metacatalogue METACATALOGUE = new Metacatalogue();

	/**
	 * No further instances allowed
	 */
	private Metacatalogue() {
		super("metacatalogue");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Datasets.DATASETS,
			Logs.LOGS,
			Settings.SETTINGS);
	}
}
