/**
 * This class is generated by jOOQ
 */
package eu.lifewatchgreece.metacatalogue.models;


import eu.lifewatchgreece.metacatalogue.models.tables.Datasets;
import eu.lifewatchgreece.metacatalogue.models.tables.Logs;
import eu.lifewatchgreece.metacatalogue.models.tables.Settings;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in metacatalogue
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table metacatalogue.datasets
	 */
	public static final Datasets DATASETS = eu.lifewatchgreece.metacatalogue.models.tables.Datasets.DATASETS;

	/**
	 * The table metacatalogue.logs
	 */
	public static final Logs LOGS = eu.lifewatchgreece.metacatalogue.models.tables.Logs.LOGS;

	/**
	 * The table metacatalogue.settings
	 */
	public static final Settings SETTINGS = eu.lifewatchgreece.metacatalogue.models.tables.Settings.SETTINGS;
}
