/**
 * This class is generated by jOOQ
 */
package eu.lifewatchgreece.metacatalogue.models.tables.records;


import eu.lifewatchgreece.metacatalogue.models.tables.Datasets;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasetsRecord extends UpdatableRecordImpl<DatasetsRecord> implements Record4<Integer, String, String, Timestamp> {

	private static final long serialVersionUID = 1186531053;

	/**
	 * Setter for <code>metacatalogue.datasets.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>metacatalogue.datasets.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>metacatalogue.datasets.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>metacatalogue.datasets.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>metacatalogue.datasets.user_email</code>.
	 */
	public void setUserEmail(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>metacatalogue.datasets.user_email</code>.
	 */
	public String getUserEmail() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>metacatalogue.datasets.created_at</code>.
	 */
	public void setCreatedAt(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>metacatalogue.datasets.created_at</code>.
	 */
	public Timestamp getCreatedAt() {
		return (Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Timestamp> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, String, String, Timestamp> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Datasets.DATASETS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Datasets.DATASETS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Datasets.DATASETS.USER_EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Datasets.DATASETS.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getUserEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatasetsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatasetsRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatasetsRecord value3(String value) {
		setUserEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatasetsRecord value4(Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DatasetsRecord values(Integer value1, String value2, String value3, Timestamp value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DatasetsRecord
	 */
	public DatasetsRecord() {
		super(Datasets.DATASETS);
	}

	/**
	 * Create a detached, initialised DatasetsRecord
	 */
	public DatasetsRecord(Integer id, String name, String userEmail, Timestamp createdAt) {
		super(Datasets.DATASETS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, userEmail);
		setValue(3, createdAt);
	}
}
