/**
 * This class is generated by jOOQ
 */
package eu.lifewatchgreece.metacatalogue.models.tables.records;


import eu.lifewatchgreece.metacatalogue.models.tables.Settings;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsRecord extends UpdatableRecordImpl<SettingsRecord> implements Record5<UInteger, String, String, Timestamp, String> {

	private static final long serialVersionUID = 1370993907;

	/**
	 * Setter for <code>metacatalogue.settings.id</code>.
	 */
	public void setId(UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>metacatalogue.settings.id</code>.
	 */
	public UInteger getId() {
		return (UInteger) getValue(0);
	}

	/**
	 * Setter for <code>metacatalogue.settings.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>metacatalogue.settings.name</code>.
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>metacatalogue.settings.value</code>.
	 */
	public void setValue(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>metacatalogue.settings.value</code>.
	 */
	public String getValue() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>metacatalogue.settings.last_modified</code>.
	 */
	public void setLastModified(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>metacatalogue.settings.last_modified</code>.
	 */
	public Timestamp getLastModified() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>metacatalogue.settings.about</code>.
	 */
	public void setAbout(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>metacatalogue.settings.about</code>.
	 */
	public String getAbout() {
		return (String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UInteger> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UInteger, String, String, Timestamp, String> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<UInteger, String, String, Timestamp, String> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field1() {
		return Settings.SETTINGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Settings.SETTINGS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Settings.SETTINGS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Settings.SETTINGS.LAST_MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Settings.SETTINGS.ABOUT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getLastModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getAbout();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value1(UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value3(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value4(Timestamp value) {
		setLastModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord value5(String value) {
		setAbout(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SettingsRecord values(UInteger value1, String value2, String value3, Timestamp value4, String value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SettingsRecord
	 */
	public SettingsRecord() {
		super(Settings.SETTINGS);
	}

	/**
	 * Create a detached, initialised SettingsRecord
	 */
	public SettingsRecord(UInteger id, String name, String value, Timestamp lastModified, String about) {
		super(Settings.SETTINGS);

		setValue(0, id);
		setValue(1, name);
		setValue(2, value);
		setValue(3, lastModified);
		setValue(4, about);
	}
}
